### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#10]
As an atam4j developer, I want the release process documented, so that I know how to release a new version using a standard and consistent way.

Document (in the project readme) the process of releasing a version. High level list of steps may be:

* manually bumping the version in pom.xml
* tagging
* creating a release in github https://github.com/atam4j/atam4j/releases
* making the released version available to maven central

PS: It is ok, if all of this is manual for now. If this is all quick to script, then do it, else can be done later. Think MVP! :)

**Comment by anuragkapur** [comment]
Documented here: https://github.com/atam4j/atam4j#release---manual
@phillbarber - please review!

**Comment by phillbarber** [comment]
Looks good, cheers
