### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#14]
Following classes have no test coverage. This needs to be addressed!
* AcceptanceTestsRunnerTask
* AcceptanceTestsHealthCheckManager
* AcceptanceTestsHealthCheck

**Comment by phillbarber** [comment]
AcceptanceTestsRunnerTask now has tests - see: https://github.com/atam4j/atam4j/pull/20

**Comment by phillbarber** [comment]
See https://github.com/atam4j/atam4j/pull/29
