### ISSUE TITLE
Report on what tests ran

### ISSUE THREAD

**Issue by phillbarber** [atam4j/atam4j#19]
This is a tricky one.  

Currently we get the message "All is ok" or "Number of failures N", when the tests have run.  There's no way to determine which tests ran.

Do we add this to the healthcheck message?  Do we expose this on a different end-point?

**Comment by TJ-Cutajar** [comment]
I think as part of the health check we should return each test name with the result, pass or fail, as a json response like so: 

    [
      {
          "test": "FooTest",
          "result": "pass"
      },
      {
          "test": "BarTest",
          "result": "fail"
      }
    ]

We could then use this to drive a simple green/red dashboard supplied on another endpoint for some visual impact (would be useful for those who don't have a monitoring solution setup). We could also add  a summary of the failure/exception within the response.

**Comment by phillbarber** [comment]
Hi Tyrone,
  I'm not sure that this is possible with the

**Comment by phillbarber** [comment]
...clicked the wrong button!

Hi Tyrone,
  That sounds like a good idea however I think that the json would need to be on a sperate endpoint.  The result of a standard healthcheck only allows a healthy boolean and description string.  Adding json into the description field would get ugly.

Your suggestion of listing each test looks good.  Anurag and I discussed simply returning the json representation of the org.junit.runner.Result  Perhaps that would be viable?  

Another option, multiple healthchecks per test e.g. /foo-test which would only return healthy if foo-test was green.  This would be easier to create individual checks for as it's just a plain old url which the monitoring plugin http_check can cover easily.

Simple green/red dashboard is in an interesting idea... Hadn't considered building support for that.  My gut tells me that if people were to use atam4j (and go through the effort neccessary to run tests in a deployed environment without relying on their build tool) then they would likely have a monitoring solution.  Might be wrong, but maybe the topic for another issue.

Cheers

**Comment by kiran-sireesh** [comment]
PR for this issue https://github.com/atam4j/atam4j/pull/34

**Comment by anuragkapur** [comment]
Experimenting with the exposing the serialised form of the `org.junit.runner.Result` on a custom jersey resource. Without any adaptation of the `Result` into a custom object, a sample response is as follows:

		{
		runCount: 3,
		runTime: 4,
		failureCount: 2,
		failures: [
		{
		message: "This test failed becuase Expected != Actual expected:<[Expected]> but was:<[Actual]>",
		exception: {
		cause: null,
		stackTrace: [
		{
		methodName: "assertEquals",
		fileName: "Assert.java",
		lineNumber: 115,
		className: "org.junit.Assert",
		nativeMethod: false
		},
		{
		methodName: "testFailure1",
		fileName: "HelloWorldTest.java",
		lineNumber: 31,
		className: "me.atam.atam4jsampleapp.tests.HelloWorldTest",
		nativeMethod: false
		},
		{
		methodName: "invoke0",
		fileName: "NativeMethodAccessorImpl.java",
		lineNumber: -2,
		className: "sun.reflect.NativeMethodAccessorImpl",
		nativeMethod: true
		},
		{
		methodName: "invoke",
		fileName: "NativeMethodAccessorImpl.java",
		lineNumber: 62,
		className: "sun.reflect.NativeMethodAccessorImpl",
		nativeMethod: false
		},
		{
		methodName: "invoke",
		fileName: "DelegatingMethodAccessorImpl.java",
		lineNumber: 43,
		className: "sun.reflect.DelegatingMethodAccessorImpl",
		nativeMethod: false
		},
		{
		methodName: "invoke",
		fileName: "Method.java",
		lineNumber: 483,
		className: "java.lang.reflect.Method",
		nativeMethod: false
		},
		{
		methodName: "runReflectiveCall",
		fileName: "FrameworkMethod.java",
		lineNumber: 47,
		className: "org.junit.runners.model.FrameworkMethod$1",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ReflectiveCallable.java",
		lineNumber: 12,
		className: "org.junit.internal.runners.model.ReflectiveCallable",
		nativeMethod: false
		},
		{
		methodName: "invokeExplosively",
		fileName: "FrameworkMethod.java",
		lineNumber: 44,
		className: "org.junit.runners.model.FrameworkMethod",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "InvokeMethod.java",
		lineNumber: 17,
		className: "org.junit.internal.runners.statements.InvokeMethod",
		nativeMethod: false
		},
		{
		methodName: "runLeaf",
		fileName: "ParentRunner.java",
		lineNumber: 271,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "BlockJUnit4ClassRunner.java",
		lineNumber: 70,
		className: "org.junit.runners.BlockJUnit4ClassRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "BlockJUnit4ClassRunner.java",
		lineNumber: 50,
		className: "org.junit.runners.BlockJUnit4ClassRunner",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 238,
		className: "org.junit.runners.ParentRunner$3",
		nativeMethod: false
		},
		{
		methodName: "schedule",
		fileName: "ParentRunner.java",
		lineNumber: 63,
		className: "org.junit.runners.ParentRunner$1",
		nativeMethod: false
		},
		{
		methodName: "runChildren",
		fileName: "ParentRunner.java",
		lineNumber: 236,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "access$000",
		fileName: "ParentRunner.java",
		lineNumber: 53,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "ParentRunner.java",
		lineNumber: 229,
		className: "org.junit.runners.ParentRunner$2",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 309,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "Suite.java",
		lineNumber: 127,
		className: "org.junit.runners.Suite",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "Suite.java",
		lineNumber: 26,
		className: "org.junit.runners.Suite",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 238,
		className: "org.junit.runners.ParentRunner$3",
		nativeMethod: false
		},
		{
		methodName: "schedule",
		fileName: "ParentRunner.java",
		lineNumber: 63,
		className: "org.junit.runners.ParentRunner$1",
		nativeMethod: false
		},
		{
		methodName: "runChildren",
		fileName: "ParentRunner.java",
		lineNumber: 236,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "access$000",
		fileName: "ParentRunner.java",
		lineNumber: 53,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "ParentRunner.java",
		lineNumber: 229,
		className: "org.junit.runners.ParentRunner$2",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 309,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 160,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 138,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 128,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "runClasses",
		fileName: "JUnitCore.java",
		lineNumber: 73,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "AcceptanceTestsRunnerTask.java",
		lineNumber: 29,
		className: "me.atam.atam4j.AcceptanceTestsRunnerTask",
		nativeMethod: false
		},
		{
		methodName: "call",
		fileName: "Executors.java",
		lineNumber: 511,
		className: "java.util.concurrent.Executors$RunnableAdapter",
		nativeMethod: false
		},
		{
		methodName: "runAndReset",
		fileName: "FutureTask.java",
		lineNumber: 308,
		className: "java.util.concurrent.FutureTask",
		nativeMethod: false
		},
		{
		methodName: "access$301",
		fileName: "ScheduledThreadPoolExecutor.java",
		lineNumber: 180,
		className: "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ScheduledThreadPoolExecutor.java",
		lineNumber: 294,
		className: "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
		nativeMethod: false
		},
		{
		methodName: "runWorker",
		fileName: "ThreadPoolExecutor.java",
		lineNumber: 1142,
		className: "java.util.concurrent.ThreadPoolExecutor",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ThreadPoolExecutor.java",
		lineNumber: 617,
		className: "java.util.concurrent.ThreadPoolExecutor$Worker",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "Thread.java",
		lineNumber: 745,
		className: "java.lang.Thread",
		nativeMethod: false
		}
		],
		message: "This test failed becuase Expected != Actual expected:<[Expected]> but was:<[Actual]>",
		actual: "Actual",
		expected: "Expected",
		localizedMessage: "This test failed becuase Expected != Actual expected:<[Expected]> but was:<[Actual]>",
		suppressed: [ ]
		},
		description: {
		empty: false,
		annotations: [
		{ }
		],
		className: "me.atam.atam4jsampleapp.tests.HelloWorldTest",
		methodName: "testFailure1",
		displayName: "testFailure1(me.atam.atam4jsampleapp.tests.HelloWorldTest)",
		children: [ ],
		suite: false,
		test: true,
		testClass: "me.atam.atam4jsampleapp.tests.HelloWorldTest"
		},
		trace: "org.junit.ComparisonFailure: This test failed becuase Expected != Actual expected:<[Expected]> but was:<[Actual]> at org.junit.Assert.assertEquals(Assert.java:115) at me.atam.atam4jsampleapp.tests.HelloWorldTest.testFailure1(HelloWorldTest.java:31) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) at org.junit.runners.ParentRunner.run(ParentRunner.java:309) at org.junit.runners.Suite.runChild(Suite.java:127) at org.junit.runners.Suite.runChild(Suite.java:26) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) at org.junit.runners.ParentRunner.run(ParentRunner.java:309) at org.junit.runner.JUnitCore.run(JUnitCore.java:160) at org.junit.runner.JUnitCore.run(JUnitCore.java:138) at org.junit.runner.JUnitCore.run(JUnitCore.java:128) at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:73) at me.atam.atam4j.AcceptanceTestsRunnerTask.run(AcceptanceTestsRunnerTask.java:29) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) ",
		testHeader: "testFailure1(me.atam.atam4jsampleapp.tests.HelloWorldTest)"
		},
		{
		message: "This test failed because 1 != 4 expected:<1> but was:<4>",
		exception: {
		cause: null,
		stackTrace: [
		{
		methodName: "fail",
		fileName: "Assert.java",
		lineNumber: 88,
		className: "org.junit.Assert",
		nativeMethod: false
		},
		{
		methodName: "failNotEquals",
		fileName: "Assert.java",
		lineNumber: 743,
		className: "org.junit.Assert",
		nativeMethod: false
		},
		{
		methodName: "assertEquals",
		fileName: "Assert.java",
		lineNumber: 118,
		className: "org.junit.Assert",
		nativeMethod: false
		},
		{
		methodName: "assertEquals",
		fileName: "Assert.java",
		lineNumber: 555,
		className: "org.junit.Assert",
		nativeMethod: false
		},
		{
		methodName: "testFailure2",
		fileName: "HelloWorldTest.java",
		lineNumber: 36,
		className: "me.atam.atam4jsampleapp.tests.HelloWorldTest",
		nativeMethod: false
		},
		{
		methodName: "invoke0",
		fileName: "NativeMethodAccessorImpl.java",
		lineNumber: -2,
		className: "sun.reflect.NativeMethodAccessorImpl",
		nativeMethod: true
		},
		{
		methodName: "invoke",
		fileName: "NativeMethodAccessorImpl.java",
		lineNumber: 62,
		className: "sun.reflect.NativeMethodAccessorImpl",
		nativeMethod: false
		},
		{
		methodName: "invoke",
		fileName: "DelegatingMethodAccessorImpl.java",
		lineNumber: 43,
		className: "sun.reflect.DelegatingMethodAccessorImpl",
		nativeMethod: false
		},
		{
		methodName: "invoke",
		fileName: "Method.java",
		lineNumber: 483,
		className: "java.lang.reflect.Method",
		nativeMethod: false
		},
		{
		methodName: "runReflectiveCall",
		fileName: "FrameworkMethod.java",
		lineNumber: 47,
		className: "org.junit.runners.model.FrameworkMethod$1",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ReflectiveCallable.java",
		lineNumber: 12,
		className: "org.junit.internal.runners.model.ReflectiveCallable",
		nativeMethod: false
		},
		{
		methodName: "invokeExplosively",
		fileName: "FrameworkMethod.java",
		lineNumber: 44,
		className: "org.junit.runners.model.FrameworkMethod",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "InvokeMethod.java",
		lineNumber: 17,
		className: "org.junit.internal.runners.statements.InvokeMethod",
		nativeMethod: false
		},
		{
		methodName: "runLeaf",
		fileName: "ParentRunner.java",
		lineNumber: 271,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "BlockJUnit4ClassRunner.java",
		lineNumber: 70,
		className: "org.junit.runners.BlockJUnit4ClassRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "BlockJUnit4ClassRunner.java",
		lineNumber: 50,
		className: "org.junit.runners.BlockJUnit4ClassRunner",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 238,
		className: "org.junit.runners.ParentRunner$3",
		nativeMethod: false
		},
		{
		methodName: "schedule",
		fileName: "ParentRunner.java",
		lineNumber: 63,
		className: "org.junit.runners.ParentRunner$1",
		nativeMethod: false
		},
		{
		methodName: "runChildren",
		fileName: "ParentRunner.java",
		lineNumber: 236,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "access$000",
		fileName: "ParentRunner.java",
		lineNumber: 53,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "ParentRunner.java",
		lineNumber: 229,
		className: "org.junit.runners.ParentRunner$2",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 309,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "Suite.java",
		lineNumber: 127,
		className: "org.junit.runners.Suite",
		nativeMethod: false
		},
		{
		methodName: "runChild",
		fileName: "Suite.java",
		lineNumber: 26,
		className: "org.junit.runners.Suite",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 238,
		className: "org.junit.runners.ParentRunner$3",
		nativeMethod: false
		},
		{
		methodName: "schedule",
		fileName: "ParentRunner.java",
		lineNumber: 63,
		className: "org.junit.runners.ParentRunner$1",
		nativeMethod: false
		},
		{
		methodName: "runChildren",
		fileName: "ParentRunner.java",
		lineNumber: 236,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "access$000",
		fileName: "ParentRunner.java",
		lineNumber: 53,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "evaluate",
		fileName: "ParentRunner.java",
		lineNumber: 229,
		className: "org.junit.runners.ParentRunner$2",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ParentRunner.java",
		lineNumber: 309,
		className: "org.junit.runners.ParentRunner",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 160,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 138,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "JUnitCore.java",
		lineNumber: 128,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "runClasses",
		fileName: "JUnitCore.java",
		lineNumber: 73,
		className: "org.junit.runner.JUnitCore",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "AcceptanceTestsRunnerTask.java",
		lineNumber: 29,
		className: "me.atam.atam4j.AcceptanceTestsRunnerTask",
		nativeMethod: false
		},
		{
		methodName: "call",
		fileName: "Executors.java",
		lineNumber: 511,
		className: "java.util.concurrent.Executors$RunnableAdapter",
		nativeMethod: false
		},
		{
		methodName: "runAndReset",
		fileName: "FutureTask.java",
		lineNumber: 308,
		className: "java.util.concurrent.FutureTask",
		nativeMethod: false
		},
		{
		methodName: "access$301",
		fileName: "ScheduledThreadPoolExecutor.java",
		lineNumber: 180,
		className: "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ScheduledThreadPoolExecutor.java",
		lineNumber: 294,
		className: "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
		nativeMethod: false
		},
		{
		methodName: "runWorker",
		fileName: "ThreadPoolExecutor.java",
		lineNumber: 1142,
		className: "java.util.concurrent.ThreadPoolExecutor",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "ThreadPoolExecutor.java",
		lineNumber: 617,
		className: "java.util.concurrent.ThreadPoolExecutor$Worker",
		nativeMethod: false
		},
		{
		methodName: "run",
		fileName: "Thread.java",
		lineNumber: 745,
		className: "java.lang.Thread",
		nativeMethod: false
		}
		],
		message: "This test failed because 1 != 4 expected:<1> but was:<4>",
		localizedMessage: "This test failed because 1 != 4 expected:<1> but was:<4>",
		suppressed: [ ]
		},
		description: {
		empty: false,
		annotations: [
		{ }
		],
		className: "me.atam.atam4jsampleapp.tests.HelloWorldTest",
		methodName: "testFailure2",
		displayName: "testFailure2(me.atam.atam4jsampleapp.tests.HelloWorldTest)",
		children: [ ],
		suite: false,
		test: true,
		testClass: "me.atam.atam4jsampleapp.tests.HelloWorldTest"
		},
		trace: "java.lang.AssertionError: This test failed because 1 != 4 expected:<1> but was:<4> at org.junit.Assert.fail(Assert.java:88) at org.junit.Assert.failNotEquals(Assert.java:743) at org.junit.Assert.assertEquals(Assert.java:118) at org.junit.Assert.assertEquals(Assert.java:555) at me.atam.atam4jsampleapp.tests.HelloWorldTest.testFailure2(HelloWorldTest.java:36) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) at org.junit.runners.ParentRunner.run(ParentRunner.java:309) at org.junit.runners.Suite.runChild(Suite.java:127) at org.junit.runners.Suite.runChild(Suite.java:26) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) at org.junit.runners.ParentRunner.run(ParentRunner.java:309) at org.junit.runner.JUnitCore.run(JUnitCore.java:160) at org.junit.runner.JUnitCore.run(JUnitCore.java:138) at org.junit.runner.JUnitCore.run(JUnitCore.java:128) at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:73) at me.atam.atam4j.AcceptanceTestsRunnerTask.run(AcceptanceTestsRunnerTask.java:29) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) ",
		testHeader: "testFailure2(me.atam.atam4jsampleapp.tests.HelloWorldTest)"
		}
		],
		ignoreCount: 0
		}

The sample response above is when there were 2 test failures and I already feel it is very noisy. So I am going to convert the default `Result` object into a concise and custom `Atam4jResults` object.

**Comment by anuragkapur** [comment]
Being addressed as part of https://github.com/atam4j/atam4j/issues/39
