### ISSUE TITLE
Update "Using Atam4j" section in readme

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#27]
The public interface has changed with https://github.com/atam4j/atam4j/pull/23 and the readme should be updated to reflect this.

**Comment by phillbarber** [comment]
I will do this once the latest release has been pushed to maven central - then I can update the sample app.

**Comment by anuragkapur** [comment]
Addressed in https://github.com/atam4j/atam4j/pull/30

**Comment by anuragkapur** [comment]
This is now complete. README associated with v0.4.0 reflects the new and improved public interface and usage code snippet.
