### ISSUE TITLE
Implement continuous integration

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#3]
As a developer, I want CI for the project so that tests and builds are run automatically on every commit and I know as soon as a commit breaks something.

Note(s)
* https://travis-ci.org/ may be used

**Comment by phillbarber** [comment]
I have signed in with travis and will also give jetpack a look too.

**Comment by anuragkapur** [comment]
@phillbarber - Thanks for adding travis! I have added a build status badge on the readme. I think this issue can now be closed. Please comment/re-open if something I have missed something.
