### ISSUE TITLE
Atam4j needs an Environment instance from dropwizard core

### ISSUE THREAD

**Issue by tjcutajar** [atam4j/atam4j#32]
Right now to build Atam4j you need an Environment instance that comes from dropwizard core. We only use this to grab a metrics registry and create a scheduled executor.

**Comment by anuragkapur** [comment]
Have updated the sample app to use v0.5.0 which includes this change.

https://github.com/atam4j/atam4j-sample-app/commit/8de9a2a1684806462bba634d2efa18065167c453

In the future, it might be a good idea to remember to keep the sample app updated with any changes to the public interface.
