### ISSUE TITLE
Add annotations to Atam4jBuilder so it can be defined in configuration yml file.

### ISSUE THREAD

**Issue by phillbarber** [atam4j/atam4j#36]
As a developer using atam4j, I want to be able to declare config in a yaml file so that the Atam4jBuilder is configured dynamically.

**Comment by anuragkapur** [comment]
@phillbarber can you please phrase this as a story (As a..., I want..., so that...) so that the requirement and the value it adds it clear? Thanks!

**Comment by anuragkapur** [comment]
@phillbarber - could you please elaborate on what you have in mind here, maybe with an example? I am not sure I have understood the requirement here. Thanks!

**Comment by phillbarber** [comment]
Can't remember what I meant... can't be bothered to try and remember!
