### ISSUE TITLE
GET /tests

### ISSUE THREAD

**Issue by phillbarber** [atam4j/atam4j#39]
Replace the current healthcheck with a resource on the above uri that returns a 200 if all tests passed in the last run or a 500 if one of them failed.
The body of the response will contain a list of each test with the test's name and status.... e.g.

[
  {"testClass":"me.atam.atam4j.dummytests.PassingTest","testName":"testThatPasses","passed":true},
  {"testClass":"me.atam.atam4j.dummytests.FailingTest","testName":"testThatFails","passed":false}
],"allTestsPassed":true}

**Comment by phillbarber** [comment]
I will be starting this this week.  If not, will let you know.

Cheers

**Comment by anuragkapur** [comment]
Cheers @phillbarber !
