### ISSUE TITLE
Maven central integration

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#4]
As a developer, I want successful releases to be uploaded to maven central so that the atam4j library is available for use to other developers.

**Comment by jitpack** [comment]
Btw, it's also easily available on https://jitpack.io/#atam4j/atam4j/1.0-SNAPSHOT

**Comment by anuragkapur** [comment]
@jitpack - will have a look. thanks for sharing!

**Comment by anuragkapur** [comment]
Raised a ticket for OSSRH integration as per documentation: http://central.sonatype.org/pages/ossrh-guide.html

https://issues.sonatype.org/browse/OSSRH-14505

**Comment by anuragkapur** [comment]
GPG keys setup using: http://central.sonatype.org/pages/working-with-pgp-signatures.html

High level summary:

1. Install gpg from https://gpgtools.org/

2. Generate key pair 
> gpg2 --gen-key      

3. List public key to get id
>  gpg2 --list-keys
pub   2048R/3248F4BF 2015-04-07
uid       [ultimate] Anurag Kapur (GPG Key) <anurag@beancrunch.com>
sub   2048R/3716E728 2015-04-07

4. Upload public key 
> gpg2 --keyserver hkp://pool.sks-keyservers.net --send-keys 3248F4BF

**Comment by anuragkapur** [comment]
https://oss.sonatype.org/content/groups/public/me/atam/atam4j/
