### ISSUE TITLE
Atam4j config file and environment variables

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#43]
As a user, 
I want to be able to define default values in environment variables for config vars defined in the yaml config file, 
so that I can declare secret vars in the config, without adding their value in source control.

Similar to how dropwizard does this.
```
mySetting: ${DW_MY_SETTING}
defaultSetting: ${DW_DEFAULT_SETTING:-default value}
```

Ref: https://dropwizard.github.io/dropwizard/manual/core.html#environment-variables

**Comment by duffj** [comment]
Looks good! :smile_cat:

**Comment by mclarke47** [comment]
+1

**Comment by tjcutajar** [comment]
I'll pick this one up.

**Comment by phillbarber** [comment]
Awesome, thanks Tyrone
