### ISSUE TITLE
Severity levels for tests

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#44]
As a user, I want to be able to define severity level to be associated with a test failure, so that the test reports can classify failures as per severity.

Example:
```
@Monitor(severity="critical")
@Test
public void myCriticalTest() throws Exception {
    // my test code
}

@Monitor(severity="major")
@Test
public void myMajorTest() throws Exception {
    // my test code
}
```

**Comment by phillbarber** [comment]
Hi Anurag,
  How will the test reports classify them?  Do you mean the /tests endpoint will also return the severity in the json body as an extra attribute?

Cheers

**Comment by anuragkapur** [comment]
Hi @phillbarber , yes, either additional attribute in the /tests json body or a separate endpoint, example /tests/{severity} that only returns tests of the given severity.

**Comment by phillbarber** [comment]
OK, cool.  Sounds good.

**Comment by anuragkapur** [comment]
Completed as part of https://github.com/atam4j/atam4j/pull/62
