### ISSUE TITLE
Bug: Incomplete results while a run is in progress

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#63]
The /tests endpoint returns an incomplete result set when a test run is in progress.
Expected: Should just return the result set from the previous run while a new run is in progress

**Comment by tjcutajar** [comment]
@anuragkapur are you still able to reproduce this?

**Comment by phillbarber** [comment]
I'll try and create a test that verifies if this is present or not.

**Comment by phillbarber** [comment]
I can reproduce this. Working on failing test and fix.

**Comment by phillbarber** [comment]
This is not an issue as proved by the test added here: https://github.com/atam4j/atam4j/pull/79
