### ISSUE TITLE
Sample App 

### ISSUE THREAD

**Issue by anuragkapur** [atam4j/atam4j#8]
As a developer, I want a sample application available which uses atam4j library available as reference to help me see how the library can be used.

**Comment by anuragkapur** [comment]
Completed and ready for review. https://github.com/atam4j/atam4j-sample-app/pull/1

**Comment by anuragkapur** [comment]
The sample app now needs updating in light of the recent changes to the public interface.

**Comment by phillbarber** [comment]
Closing this since it looks like the sample app works fine with the latest changes.  Feel free to re-open if I have missed something.
